import TestIcon from './TestIcon';

export default function Home() {
  const title = "Home";
  return (
      <div>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
          <TestIcon/>
      </div>
  );
}
